### ISSUE TITLE
A publicly @scoped module, being required in an npme @scoped module, breaks `npm install`

### ISSUE THREAD

**Issue by kevinSuttle** [npm/registry-issue-archive#19]
_Documenting here for @bcoe._ 

If you require a publicly-scoped module like https://www.npmjs.com/package/@kadira/storybook as a dependency (not devDependency), in a module published to npme, consumers of that npme module will see an error when trying to install it. It requires either:
1. Moving the publicly-scoped package to devDependencies, or
2. Explicitly install it after the fact.

**Comment by kevinSuttle** [comment]
Confirmed that a `postinstall` script works as a temporary fix, but the problem then becomes that the package is re-added to `dependencies`, which, if left unchecked, will trigger this problem again.

**Comment by kevinSuttle** [comment]
A dead-end that some may attempt for a workaround: use a git URL. This doesn't work for GitHub Enterprise if your system is set up to sync with LDAP/SAML/OAuth and you don't use username/password combos to log in.

**Comment by kevinSuttle** [comment]
For the time being, the safest strategy seems to be `optionalDependencies`.
https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by kevinSuttle** [comment]
This is the one time I would want to be able to put a comment in a package.json file. https://github.com/npm/npm/issues/4482

**Comment by nexdrew** [comment]
@kevinSuttle I believe this is because of a known issue with the changes feed from the public registry - basically the feed does not yet include public scoped packages, which means they are missing from public replicas that npm Enterprise uses as its default upstream registry.

Our team is actively working on this problem, but until we fix it upstream, I think you'll need to manually publish public scoped packages to your npm Enterprise registry. You can do this via the following:
1. Download and extract the tarball from the public registry
   
   ```
   export PACKAGE=@kadira/storybook
   curl `npm info $PACKAGE dist.tarball --registry https://registry.npmjs.org` | tar xz
   ```
2. Publish the contents as is to your npm Enterprise registry
   
   ```
   npm publish package --ignore-scripts --registry http://registry.myco.com:8080
   ```
3. Remove the extracted contents
   
   ```
   rm -rf package
   ```

You should be able to repeat these steps in a loop if there are several public scoped packages you need to manually replicate. See [my bash script](https://gist.github.com/nexdrew/8944bb8725edaaa72afa2509cd715d78) as an example.

I'm fairly certain this won't cause issues going forward (e.g. conflicts from upstream), but we might want to get opinions from others first.

cc @bcoe

**Comment by kevinSuttle** [comment]
@nexdrew Can't we whitelist `@scoped` packages from the public registry via the npme UI or CLI to replicate to npme's registry?

**Comment by kevinSuttle** [comment]
```
~# npmo add-package @kadira/storybook
analyzing dependencies for @kadira/storybook:
Cannot convert undefined or null to object
[]
[?] add dependencies to /etc/npme/data/whitelist? Yes
success!
```

maybe not...

**Comment by kevinSuttle** [comment]
And also, putting in postinstall or pre-publish is a no-go...
https://github.com/npm/npm/issues/3059

**Comment by nexdrew** [comment]
@kevinSuttle Public scoped packages can be added to an npm Enterprise whitelist, but until the changes feed from the upstream public registry includes those packages, npm Enterprise is unable to replicate them automatically.

It looks like there is probably a bug in the `npme` bin (formerly known as `npmo`) as well, which we can fix, but that won't be useful until npm Enterprise can fetch public scoped packages from the upstream public registry/replica.

In the meantime, I think using my script to manually (1) download packages from the public registry and (2) publish them to your private registry is the easiest workaround.

**Comment by raybooysen** [comment]
@kevinSuttle what is the ETA on this fix?  If we publish manually, we don't get updates (obviously) so we are constantly having to put aside time to do this manual process.

**Comment by kevinSuttle** [comment]
@raybooysen No idea. I don't work at npm. :)

**Comment by soldair** [comment]
@raybooysen the feature this depends on, a "scoped" changes feed. afaik this is weeks rather than months away from public release. I expect after its available it will not be much longer to use it for npme.

**Comment by raybooysen** [comment]
@soldair I've just tried the script to publish myself and seeing this as an output:

```
npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "@kadira/storybook" "--verbose"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 failed to proxy package JSON from remote : @kadira/storybook-ui
npm ERR! 404 
npm ERR! 404  '@kadira/storybook-ui' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@kadira/storybook'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ray/tmp/npm-debug.log
```

**Comment by raybooysen** [comment]
Ah I see.  Seems the dependencies that are also scoped need to be installed by hand...

**Comment by nexdrew** [comment]
**UPDATE**: I'm happy to announce that, thanks to the hard work of the registry team, there is now a replication endpoint that includes public scoped packages:

```
https://replicate.npmjs.com
```

We have also (as of release `3448a1c (310)`) updated the default Upstream Registry URL in npm Enterprise to leverage this and fixed a bug with `npme add-package` that prevented it from working with scoped packages.

**Note** that existing npm Enterprise instances will not start using the new default endpoint just by performing an upgrade - you will also need to manually change the Upstream Registry URL in Settings to point to the URL above. After doing so, restart the appliance to pick up the change (for which you will be prompted) and either kick off a full reindex of packages via `npme reset-follower` or manually add the public scoped packages you're interested in via `npme add-package @scoped/pkg-name`.

New npm Enterprise instances will use the new replication endpoint by default.

**Comment by raybooysen** [comment]
Hi @nexdrew 
What do we do with manually published packages if we followed your steps above?  Will the new syncing mechanism overwrite these?

**Comment by nexdrew** [comment]
@raybooysen No, existing versions will not be overwritten, they will simply be skipped during replication.

However, we need to make sure the upstream packages will be included in your replication policy.

For folks running a full mirror of the public registry, no extra steps should be needed beyond those described above (update Upstream Registry URL, restart appliance, run `npme reset-follower`).

For folks using a white-list policy, you will need to do one of the following in addition to the steps above:
- Use `npme add-package @scope/pkg` to add the upstream packages (that you previously replicated manually) to your whitelist file for automatic replication (see note on bugs below).
- Make sure the Read Through Cache setting is enabled, run `npme remove-package @scope/pkg` for the packages you manually replicated before, and then run `npm install @scope/pkg` while pointing to your npm Enterprise registry (either via `~/.npmrc` file or using the `--registry` CLI option).

Please note there are a couple known bugs with `npme add-package` concerning scoped packages that we will be working to fix:
1. An unversioned package specification (e.g. `@kadira/storybook`) is translated into a versioned package spec (e.g. `@kadira/storybook@1.34.1`) for the target package and its dependencies, when added to the whitelist file. This will limit the replication to those specific versions, even when the `--all-versions` flag is given on the command line. **UPDATE** This has been fixed as of `npme@4.1.2`.
2. Packages that only have prerelease versions (e.g. `2.0.0-rc.3`) must include the version in the package specification (e.g. `@angular/core@2.0.0-rc.3`). Otherwise, the command is unable to determine a suitable version and will output this message: `could not find a satisfactory version for string *` **UPDATE** This has been fixed as of appliance release `b25c40a (312)`. Please update your npm Enterprise appliance via the admin console at your convenience.

**Comment by nexdrew** [comment]
As a temporary workaround for the first `npme add-package` bug mentioned above, you can instead use `replicated admin add-package @scope/pkg`:

``` sh
# converts unversioned to versioned
$ npme add-package @aquabat/issue-19
analyzing dependencies for @aquabat/issue-19:
[
  "@aquabat/issue-19@2.0.0"
]
[?] add dependencies to /etc/npme/data/whitelist? (Y/n)

# uses unversioned
$ replicated admin add-package @aquabat/issue-19
analyzing dependencies for @aquabat/issue-19:
[
  "@aquabat/issue-19"
]
[?] add dependencies to /etc/npme/data/whitelist? (Y/n)
```

**Comment by nexdrew** [comment]
The first bug:

> An unversioned package specification is translated into a versioned package spec

has been fixed as of `npme@4.1.2` (see https://github.com/npm/npme-installer/pull/147).

To update your `npme` bin **without affecting your running instance**, run:

```
sudo npm i -g --ignore-scripts npme
```

**Comment by nexdrew** [comment]
The second bug:

> Packages that only have prerelease versions must include the version in the package specification

has been fixed as of appliance release `b25c40a (312)` (see https://github.com/npm/npme-docker/pull/85).

To grab this fix, please update your npm Enterprise appliance by going the to Dashboard in the admin console, clicking the "Check Now" button to check for a new release, and then the "Install" button for the most recent release. **Note** that this will incur downtime of the appliance (registry and website) until the upgrade is complete.

**Comment by nexdrew** [comment]
AFAIK this issue has been resolved as of the following:
- Use of `https://replicate.npmjs.com` as your upstream registry
- Appliance release `b25c40a (312)`
- `npme` bin version `4.1.2`

Please see prior comments for details. If you still encounter issues with support for public scoped packages in your npm Enterprise instance, please let us know and open another issue (either here or [here](https://github.com/npm/npme-installer/issues)). Thanks!

**Comment by raybooysen** [comment]
We followed these instructions last night, upgraded to the latest version of npme, upgraded the full set of docker components, changed the replication URL, restarted and reset the follower.

Today, trying to install today, we see the following logs:

```
npm install] npm ERR! Windows_NT 6.3.9600
[08:54:50][npm install] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
[08:54:50][npm install] npm ERR! node v5.7.1
[08:54:50][npm install] npm ERR! npm  v3.6.0
[08:54:50][npm install] 
[08:54:50][npm install] npm ERR! shasum check failed for D:\BuildAgent\temp\buildTmp\npm-3420-8ee3168e\10.50.1.41_8080\_40\_40kadira\react-split-pane\_attachments\react-split-pane-1.4.7.tgz
```

We've cleared the npm cache on the build servers, and everyone's PCs and still seeing this error.

This only occurs around this scoped package.

**Comment by bcoe** [comment]
@raybooysen mind providing `--verbose` output from the npm install?

Just ran this and it works great:

```
npm cache clear; npm i @kadira/react-split-pane --registry=http://my-registry:8080 --verbose
```

Running the install with `--verbose` will tell us if you're running headlong into a firewall, or something similar; keep in mind `https://replicate.npmjs.com` needs to be allowed through. A couple other things:

If you're using Atlassian BitBucket, or Github Enterprise auth, you need to turn off auth for reads, to be able to use scoped public modules:

<img width="833" alt="screen shot 2016-07-01 at 9 31 31 am" src="https://cloud.githubusercontent.com/assets/194609/16527995/bc23e3e2-3f6e-11e6-8bed-179dcbdcb1fd.png">

Here's what the configuration should look like for replication:

<img width="792" alt="screen shot 2016-07-01 at 9 31 20 am" src="https://cloud.githubusercontent.com/assets/194609/16528003/c5435ef8-3f6e-11e6-9742-7f38f7509d08.png">

Also, are you using read-through-cache or full mirror mode? If you're using a full mirror, you might need to wait for the registry to sync before you have scoped modules.

**Comment by kevinSuttle** [comment]
This still seems to be a problem for modules scoped within an npme registry. Most of the time, a package.json will consist of modules from public registry as a majority. If you `npm config set registry "mycustomnpmeserver.biz"` then every request is going to go through that. 

I think a smarter approach to all of this is to section off registries and/or scopes in package.json, maybe in `publishConfig`. I'm wondering why npm doesn't look for other registries you've specified before giving up.

**Comment by gusdaud-zz** [comment]
I'm having a similar issue. My package.json dependencies uses something that's in a NPMe  

```
"dependencies": {
  "@myscope/mypackage": "0.0.1"
```

This NPMe repository address is set the NPM config.

```
npm config set @myrepo:registry http://200.168.7.1
```

(although main `registry` entry in npm config still points to official public repo)

When I do `npm install` I'm getting this error:

```
'@myscope/mypackage' is not in the npm registry.
```

Shouldn't NPM be also looking for this package in the NPMe repository when I do `npm install` ?

_ps I'm using npm version 3.10.5_

**Comment by nexdrew** [comment]
@gusdaud This doesn't sound related to replication of public scoped packages, so we may want to open an issue here instead: https://github.com/npm/npme-installer/issues

That being said, make sure the scope you use in your package name matches one that is mapped to your registry in `.npmrc` (looks like your comment has a typo in the `npm config` command, should use `@myscope:registry` instead of `@myrepo:registry`).

Also make sure you are routing your registry address to port 8080 on the npm Enterprise host (the registry service currently binds to port 8080).

Other than that, what type of authentication are you using? Do you have read access to the repo listed in `@myscope/mypackage`'s package.json (under `repository` > `url`)? Do you have the _Auth Scoped Installs_ setting enabled in the admin console?

**Comment by gusdaud-zz** [comment]
@nexdrew Thanks a lot.

I've solved my issue and documented it here https://github.com/npm/npme-installer/issues/149 in hope that it may help others.

**Comment by kevinSuttle** [comment]
It seems like this is an issue that perhaps could be resolved by [hook scripts](https://docs.npmjs.com/misc/scripts#hook-scripts), considering the behavior npm suffers from is the inability to look at more than one registry at a time.

**Comment by kevinSuttle** [comment]
@nexdrew Still an issue. Even running `npme add-package` doesn't resolve this. Try with `@kadira/react-storybook-addon-info`.

**Comment by bcoe** [comment]
@kevinSuttle I think we got this mostly working? upgrading hardware might be needed to get everything running smoothly as we ultimately want (which I'll be in touch about).
