### ISSUE TITLE
Published package does not show up in the registry immediately

### ISSUE THREAD

**Issue by egoist** [npm/registry-issue-archive#318]
I just published a package, but it's been 5 minutes and npm is still returning the cached version.

Following screenshots are taken at the same time:

<img width="540" alt="2018-05-10 9 19 24" src="https://user-images.githubusercontent.com/8784712/39871577-e6bb9ad8-5497-11e8-93e8-572373e944d7.png">
<img width="619" alt="2018-05-10 9 19 31" src="https://user-images.githubusercontent.com/8784712/39871581-e871525a-5497-11e8-98cd-cb73c61a0c52.png">

**Comment by egoist** [comment]
I'm closing this because now the package has been updated properly on npm registry, but I always need to wait for 5 to 10 minutes for the registry to actually update..

**Comment by egoist** [comment]
Re-opened because it happens again when I publish a new version..

**Comment by crash7** [comment]
Same here, private package, new versions are not showing up in the site or when we run npm install package

Update: now one of the versions I published 30 minutes ago is showing up.

**Comment by soldair** [comment]
thanks for letting us know. I'm taking a look at this issue for private packages still. hopefully ill have it sorted very soon

**Comment by shubhanshusingh** [comment]
I am facing same issue for private packages.Got the mail that it got published, but unable to install it somewhere else as it says `target not found` and displays list of older versions of package.

**Comment by fathyb** [comment]
Same here, public package `parcel-plugin-typescript`. Just published two versions (`0.8.0-next.1` and `0.8.0-next.2`) and I can't find them in the registry despite the confirmation mails.

**Comment by ef4** [comment]
I suspect the issue is affecting all namespaced packages, not just private ones, because we are waiting on several public namespaced packages to appear.

Example: `@cardstack/authentication` 0.7.10 was published successfully at 12:28 EDT (40 minutes ago at the time of this comment), and it's still not visible.

**Comment by soldair** [comment]
this should be resolved. if anyone is still not seeing a version they know should be there please contact support and ill look into it =)

**Comment by egoist** [comment]
hmm that seems to be resolved but some other issue happens here:

<img width="735" alt="2018-05-15 12 07 35" src="https://user-images.githubusercontent.com/8784712/40009132-bd9e5b92-57d3-11e8-9feb-05bd9e8cf69c.png">

I just added `egoist` to the package `vue-feather-icons`, it's updated on the website itself but npm registry does not get updated..

<img width="317" alt="2018-05-15 12 08 09" src="https://user-images.githubusercontent.com/8784712/40009217-fc2711c4-57d3-11e8-8f28-5624dd3c4759.png">

**Comment by amorist** [comment]
same issue

**Comment by egoist** [comment]
I'm really frustrated that it's still not solved. I added `egoist` to package `ream` and the npm registry is yet updated after days of waiting..

<img width="703" alt="2018-05-19 9 13 30" src="https://user-images.githubusercontent.com/8784712/40268931-5835c748-5ba9-11e8-9fee-5785b3a711fb.png">


<img width="583" alt="2018-05-19 9 15 19" src="https://user-images.githubusercontent.com/8784712/40268937-732840e4-5ba9-11e8-9ef0-e3061a16e80f.png">

**Comment by soldair** [comment]
\o please email support@npmjs.com if you have any issues that  especially if its been days, we're happy to look into your specific issue

**Comment by oleics** [comment]
Same here: https://registry.npmjs.org/ac-json-apis
should be 0.0.6, but is stuck at 0.0.5 since several hours

**Comment by rarkins** [comment]
@soldair FYI it's happening again big time

**Comment by schalkneethling** [comment]
Same here, on the packages view it shows the correct version but, when I go to the modules individual page, there is a version mismatch. Also, installing with `npm i -D --save-exact <package-name>` I do not get the latest version.

**Comment by schalkneethling** [comment]
The page listing the package now correctly reflects the latest version but, npm i still installs the old version. Progress, yay. Thanks!

**Comment by dawnerd** [comment]
Will this https://status.npmjs.org/incidents/3rjzvts6v98k get older publishes up to date?

npm show still shows old version - not matching site
